name: practice_data_platform
version: "1.0.0"
config-version: 2

profile: practice_data_platform

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

models:
  practice_data_platform:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
