-- Snowflakeインフラ構築（.steering/20260922-snowflake-infra-setup）
-- docs/architecture.md および design.md の内容を実際に構築するスクリプト。
-- Snowsightのワークシートに貼り付けて実行する。
--
-- 個人・単一ユーザーのアカウントのため、SYSADMIN/SECURITYADMINには分けず、
-- ACCOUNTADMINロールのまま一括で実行する。

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- 1. ウェアハウス作成
-- ============================================================
CREATE WAREHOUSE IF NOT EXISTS MAIN_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    COMMENT = 'practice_data_platform: 共有ウェアハウス（用途別に分割しない）';

-- ============================================================
-- 2. リソースモニター作成・ウェアハウスへの紐付け
--    ※CREDIT_QUOTAは暫定値。契約プランのクレジット単価が判明次第、
--      月額1,000円未満（docs/requirements.md）に収まる値へ調整する。
-- ============================================================
CREATE RESOURCE MONITOR IF NOT EXISTS MONTHLY_BUDGET_MONITOR
    WITH
        CREDIT_QUOTA = 10
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 25 PERCENT DO NOTIFY
        ON 50 PERCENT DO NOTIFY
        ON 75 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE MAIN_WH SET RESOURCE_MONITOR = MONTHLY_BUDGET_MONITOR;

-- ============================================================
-- 3. データベース作成
-- ============================================================
CREATE DATABASE IF NOT EXISTS RAW_PROD COMMENT = '取得元システムからの生データ（本番）';
CREATE DATABASE IF NOT EXISTS RAW_DEV COMMENT = '取り込みロジックの開発・動作確認用';
CREATE DATABASE IF NOT EXISTS ANALYTICS_PROD COMMENT = 'dbtによる変換結果（本番）';
CREATE DATABASE IF NOT EXISTS ANALYTICS_DEV COMMENT = 'dbtによる変換結果（開発）';

-- ============================================================
-- 4. スキーマ作成
-- ============================================================
CREATE SCHEMA IF NOT EXISTS RAW_PROD.MONEYFORWARD;
CREATE SCHEMA IF NOT EXISTS RAW_DEV.MONEYFORWARD;

CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.MARTS;

CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.MARTS;

-- ============================================================
-- 5. ロール作成
-- ============================================================
CREATE ROLE IF NOT EXISTS LOADER_DEV;
CREATE ROLE IF NOT EXISTS LOADER_PROD;
CREATE ROLE IF NOT EXISTS TRANSFORMER_DEV;
CREATE ROLE IF NOT EXISTS TRANSFORMER_PROD;
CREATE ROLE IF NOT EXISTS REPORTER_DEV;
CREATE ROLE IF NOT EXISTS REPORTER_PROD;

-- ============================================================
-- 6. 権限付与
--    docs/architecture.md「ロール・権限設計」の通り、環境を跨いだ
--    参照・書き込み権限は一切付与しない。
-- ============================================================

-- --- LOADER_DEV：RAW_DEVへの書き込みのみ ---
GRANT USAGE ON DATABASE RAW_DEV TO ROLE LOADER_DEV;
GRANT USAGE ON SCHEMA RAW_DEV.MONEYFORWARD TO ROLE LOADER_DEV;
GRANT CREATE TABLE ON SCHEMA RAW_DEV.MONEYFORWARD TO ROLE LOADER_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RAW_DEV.MONEYFORWARD TO ROLE LOADER_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RAW_DEV.MONEYFORWARD TO ROLE LOADER_DEV;
GRANT USAGE ON WAREHOUSE MAIN_WH TO ROLE LOADER_DEV;

-- --- LOADER_PROD：RAW_PRODへの書き込みのみ ---
GRANT USAGE ON DATABASE RAW_PROD TO ROLE LOADER_PROD;
GRANT USAGE ON SCHEMA RAW_PROD.MONEYFORWARD TO ROLE LOADER_PROD;
GRANT CREATE TABLE ON SCHEMA RAW_PROD.MONEYFORWARD TO ROLE LOADER_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RAW_PROD.MONEYFORWARD TO ROLE LOADER_PROD;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RAW_PROD.MONEYFORWARD TO ROLE LOADER_PROD;
GRANT USAGE ON WAREHOUSE MAIN_WH TO ROLE LOADER_PROD;

-- --- TRANSFORMER_DEV：RAW_DEVの参照、ANALYTICS_DEVへの書き込み ---
GRANT USAGE ON DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;
GRANT USAGE ON SCHEMA RAW_DEV.MONEYFORWARD TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DEV.MONEYFORWARD TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_DEV.MONEYFORWARD TO ROLE TRANSFORMER_DEV;

GRANT USAGE ON DATABASE ANALYTICS_DEV TO ROLE TRANSFORMER_DEV;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_DEV.STAGING TO ROLE TRANSFORMER_DEV;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_DEV.INTERMEDIATE TO ROLE TRANSFORMER_DEV;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_DEV.MARTS TO ROLE TRANSFORMER_DEV;

GRANT USAGE ON WAREHOUSE MAIN_WH TO ROLE TRANSFORMER_DEV;

-- --- TRANSFORMER_PROD：RAW_PRODの参照、ANALYTICS_PRODへの書き込み ---
GRANT USAGE ON DATABASE RAW_PROD TO ROLE TRANSFORMER_PROD;
GRANT USAGE ON SCHEMA RAW_PROD.MONEYFORWARD TO ROLE TRANSFORMER_PROD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_PROD.MONEYFORWARD TO ROLE TRANSFORMER_PROD;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_PROD.MONEYFORWARD TO ROLE TRANSFORMER_PROD;

GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE TRANSFORMER_PROD;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.STAGING TO ROLE TRANSFORMER_PROD;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.INTERMEDIATE TO ROLE TRANSFORMER_PROD;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS_PROD.MARTS TO ROLE TRANSFORMER_PROD;

GRANT USAGE ON WAREHOUSE MAIN_WH TO ROLE TRANSFORMER_PROD;

-- --- REPORTER_DEV：ANALYTICS_DEV.MARTSの参照のみ ---
GRANT USAGE ON DATABASE ANALYTICS_DEV TO ROLE REPORTER_DEV;
GRANT USAGE ON SCHEMA ANALYTICS_DEV.MARTS TO ROLE REPORTER_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_DEV.MARTS TO ROLE REPORTER_DEV;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_DEV.MARTS TO ROLE REPORTER_DEV;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_DEV.MARTS TO ROLE REPORTER_DEV;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_DEV.MARTS TO ROLE REPORTER_DEV;
GRANT USAGE ON WAREHOUSE MAIN_WH TO ROLE REPORTER_DEV;

-- --- REPORTER_PROD：ANALYTICS_PROD.MARTSの参照のみ ---
GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE REPORTER_PROD;
GRANT USAGE ON SCHEMA ANALYTICS_PROD.MARTS TO ROLE REPORTER_PROD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_PROD.MARTS TO ROLE REPORTER_PROD;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_PROD.MARTS TO ROLE REPORTER_PROD;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS_PROD.MARTS TO ROLE REPORTER_PROD;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS_PROD.MARTS TO ROLE REPORTER_PROD;
GRANT USAGE ON WAREHOUSE MAIN_WH TO ROLE REPORTER_PROD;

-- ============================================================
-- 7. 個人ユーザーへのロール付与（ユーザーは1つのみ、USE ROLEで切り替える）
-- ============================================================
GRANT ROLE LOADER_DEV TO USER TOMITAYUKI;
GRANT ROLE LOADER_PROD TO USER TOMITAYUKI;
GRANT ROLE TRANSFORMER_DEV TO USER TOMITAYUKI;
GRANT ROLE TRANSFORMER_PROD TO USER TOMITAYUKI;
GRANT ROLE REPORTER_DEV TO USER TOMITAYUKI;
GRANT ROLE REPORTER_PROD TO USER TOMITAYUKI;

-- ============================================================
-- 8. MFA有効化について
--    MFAはSQLではなくSnowsightのUI操作（ユーザーメニュー→Enroll in MFA）
--    で行うため、本スクリプトの対象外。tasklist.mdのタスク2で別途案内する。
-- ============================================================
